# Generated by Django 5.0 on 2025-09-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_amount_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='amount_left',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
